-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add the embedding column to the listings table if it doesn't exist
-- This column will store the vector embeddings generated by OpenAI
ALTER TABLE listings
ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Create an IVFFlat index for efficient similarity search
-- 'lists' parameter: number of clusters, typically sqrt(num_rows)
-- For small datasets, 100 lists works well and scales to larger datasets
CREATE INDEX IF NOT EXISTS listings_embedding_idx
ON listings
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create a function for semantic search based on mood
-- This function takes a query embedding, a similarity threshold, and a match count
CREATE OR REPLACE FUNCTION match_listings_by_mood(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 50
)
RETURNS TABLE (
  id uuid,
  title text,
  description text,
  price numeric,
  moods text,
  styles text,
  intents text,
  category text,
  primary_image_url text,
  seller_id uuid,
  created_at timestamptz,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    l.id,
    l.title,
    l.description,
    l.price,
    l.moods,
    l.styles,
    l.intents,
    l.category,
    COALESCE(l.original_image_url, l.clean_image_url, l.staged_image_url, l.photo_url) as primary_image_url,
    l.seller_id,
    l.created_at,
    1 - (l.embedding <=> query_embedding) as similarity -- Cosine distance to similarity
  FROM listings l
  WHERE
    l.status = 'active'
    AND l.embedding IS NOT NULL
    AND 1 - (l.embedding <=> query_embedding) > match_threshold -- Filter by similarity
  ORDER BY l.embedding <=> query_embedding -- Order by closest match
  LIMIT match_count;
END;
$$;

CREATE EXTENSION IF NOT EXISTS vector;

-- Add the embedding column to the listings table if it doesn't exist
-- This column will store the vector embeddings generated by OpenAI
ALTER TABLE listings
ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Create an IVFFlat index for efficient similarity search
-- 'lists' parameter: number of clusters, typically sqrt(num_rows)
-- For small datasets, 100 lists works well and scales to larger datasets
CREATE INDEX IF NOT EXISTS listings_embedding_idx
ON listings
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Create a function for semantic search based on mood
-- This function takes a query embedding, a similarity threshold, and a match count
CREATE OR REPLACE FUNCTION match_listings_by_mood(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 50
)
RETURNS TABLE (
  id uuid,
  title text,
  description text,
  price numeric,
  moods text,
  styles text,
  intents text,
  category text,
  primary_image_url text,
  seller_id uuid,
  created_at timestamptz,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    l.id,
    l.title,
    l.description,
    l.price,
    l.moods,
    l.styles,
    l.intents,
    l.category,
    COALESCE(l.original_image_url, l.clean_image_url, l.staged_image_url, l.photo_url) as primary_image_url,
    l.seller_id,
    l.created_at,
    1 - (l.embedding <=> query_embedding) as similarity -- Cosine distance to similarity
  FROM listings l
  WHERE
    l.status = 'active'
    AND l.embedding IS NOT NULL
    AND 1 - (l.embedding <=> query_embedding) > match_threshold -- Filter by similarity
  ORDER BY l.embedding <=> query_embedding -- Order by closest match
  LIMIT match_count;
END;
$$;




